# Generated by Django 5.0.4 on 2024-05-10 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0002_remove_profile_confirmation_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
    ]
