# Generated by Django 5.0.4 on 2024-05-13 03:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_news'),
        ('userApp', '0004_productlike_productrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlike',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_profiles', to='mainApp.product'),
        ),
        migrations.AlterField(
            model_name='productlike',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productrate',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rated_profiles', to='mainApp.product'),
        ),
        migrations.AlterField(
            model_name='productrate',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rated_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='productlike',
            unique_together={('product', 'profile')},
        ),
        migrations.AlterUniqueTogether(
            name='productrate',
            unique_together={('product', 'profile')},
        ),
    ]
